### ISSUE TITLE
Can't see numeric values in ESDR chart at peak

### ISSUE THREAD

**Issue by rsargent** [CMU-CREATE-Lab/esdr#12]
Good -- shows numbers below peak:

![image](https://user-images.githubusercontent.com/324851/55156259-d461c200-512f-11e9-9cc7-46de78fdf822.png)

Bad -- numbers at peak draw off the edge and aren't legible:

![image](https://user-images.githubusercontent.com/324851/55156310-f1969080-512f-11e9-89bd-b8173b72eae2.png)

**Comment by chrisbartley** [comment]
It's probably not too hard of a fix.  It's still using the old BodyTrack grapher, which has pretty good support for custom styles.  We might be able to just adjust the style to show the value *below* the data point on hover.  We'll then run into a similar problem for near-zero values at the bottom of the plot, but maybe that matters less.  There *should* also be an option to automatically add padding to both ends of the y-axis range, so I could also make sure that's enabled.  As a last resort, I have examples of other ways to report values--on hover and/or with the cursor--so that's an option too.  For example:

	http://bodytrack.github.io/plot-manager/examples/bodytrack-grapher/index10.html
