### ISSUE TITLE
Can't see numeric values on Y axis for Avalon SO2 and H2S

### ISSUE THREAD

**Issue by rsargent** [CMU-CREATE-Lab/esdr#14]
Avalon SO2 and HS2 tend to be values like 0.001.  But there's not enough space on the right to display so many digits, so it shows as 0.00.  Need more space to the right:

Link: https://esdr.cmucreatelab.org/browse/#channels=1.SO2_PPM,1.H2S_PPM&time=1354704319.2479482,1562154466.977544&zoom=3&center=49.35720091782239,-92.91969375610347&cursor=1554322435.693&search=liberty

![image](https://user-images.githubusercontent.com/324851/55510495-671cc800-562c-11e9-80af-564ebbf2c13f.png)

**Comment by chrisbartley** [comment]
It's probably not too hard of a fix.  It's still using the old BodyTrack grapher, which has pretty good support for custom styles.  We might be able to just adjust the style to show the value *below* the data point on hover.  We'll then run into a similar problem for near-zero values at the bottom of the plot, but maybe that matters less.  There *should* also be an option to automatically add padding to both ends of the y-axis range, so I could also make sure that's enabled.  As a last resort, I have examples of other ways to report values--on hover and/or with the cursor--so that's an option too.  For example:

	http://bodytrack.github.io/plot-manager/examples/bodytrack-grapher/index10.html
