### ISSUE TITLE
/explore.  Zooming out shows bizarre bars

### ISSUE THREAD

**Issue by rsargent** [CMU-CREATE-Lab/esdr#23]
It's 51% degrees humidity from 2014 to 2021? 

https://environmentaldata.org/#channels=12267.humidity&time=965135518.719,2114627530.393&plotHeight=5.000&plotAreaHeight=60.000&showSparklines=true&showFilters=true&showSettings=true&showResults=true&center=49.12141069773241,-77.5349625&zoom=6

![image](https://user-images.githubusercontent.com/324851/101033382-2a634b80-3548-11eb-9e44-a6bea2c59a54.png)

These seem to flash strangely, possibly as different levels of tile resolution load?

Seems likely to be a problem around determining bar width.

**Comment by rsargent** [comment]
Zooming in on purple air also looks difficult to explain.  I see a wide variety of bar widths and wide variety of gaps between the bars.  It seems confusing

https://environmentaldata.org/#channels=1.BP_MM_HG,27410.PM2_5&time=1605365630.427,1605370062.550&plotHeight=5.000&plotAreaHeight=40.000&showSparklines=true&showFilters=true&showSettings=true&showResults=true&center=40.446945528715595,-79.9331479356612&zoom=15&recentOnly=true&mapOnly=true

![image](https://user-images.githubusercontent.com/324851/101038599-a0b47d80-3549-11eb-9510-63bff62eafc1.png)

**Comment by dognotdog** [comment]
What would you want this to look like? This is super tricky because one can't just use the natural "tile" spacing, as sparsely populated tiles (which all are zoomed in far enough) end up looking weird. And there are often artifacts where a tile would have just one sample pair real close to each other, the rest spaced out, so just using the same smallest width for all samples also looks weird. 

So right now what happens is that each bar is expanded to maximally fill the space it has around it to the next bar. If the data is irregular, that's what it looks like.

**Comment by rsargent** [comment]
Let's talk at 1130.  Is it an option to use lines?

**Comment by dognotdog** [comment]
There are many options, we just have to find a good one :)

**Comment by dognotdog** [comment]
what points could look like: 
<img width="682" alt="image" src="https://user-images.githubusercontent.com/1443151/101064089-9900d300-3561-11eb-8fd7-606c8dfaffe7.png">

**Comment by dognotdog** [comment]
and lines: 
<img width="685" alt="image" src="https://user-images.githubusercontent.com/1443151/101064386-f3019880-3561-11eb-8f33-ac5cc7dfa545.png">

**Comment by chrisbartley** [comment]
FWIW, the old bodytrack grapher solves the bar width problem by having you define a width (in seconds, IIRC) for each sample, and whether the bar should be centered on the sample timestamp, leading it, or trailing it (with centered being the default, I believe).  For pretty much any sensor I can think of at the moment, they sample at regular intervals (e.g. Airnow at 1 hour, CREATE Lab VOC at 30s, Airviz VOC+PM at 1s, etc), so this should be fairly reasonable thing to do.  

Rather than hardcoding sample width in the viz, it _could_ be stored in the product's `defaultChannelSpecs` field, which gets copied to a feed's channelSpecs field upon feed creation.  However, as with all things ESDR at the moment, these fields aren't editable via the API.  But I know the guy who could do it in SQL... ;-)

**Comment by AnaHoffman** [comment]
For the record, I'm not a fan of dots at first glance.

Best,
Ana Hoffman
CREATE Lab
Email: ana@createlab.org
Cell: (304) 231-7547
