### ISSUE TITLE
/explore:  Intel graphics driver causes vertical offset in sensor markers

### ISSUE THREAD

**Issue by rsargent** [CMU-CREATE-Lab/esdr#30]
map markers are drawn offset in latitude on computers with Intel GPUs

**Comment by dognotdog** [comment]
should be fixed as of 4808afa, having moved the non-linear mercator projection to outside the shader

**Comment by AnaHoffman** [comment]
Awesome!! I'll check soon!

**Comment by pdille** [comment]
@dognotdog Looks to be working on my machine when I set to use Intel only. @AnaHoffman I don't think this fix is on the live site yet, but do test when it is. I was testing locally on my machine, which was a faster way to confirm.

@dognotdog Since this topic is about click related things, what do you think about disabling the pointer that shows up for POI on the google maps base layer? You can easily do this via this maps flag:  `clickableIcons: false`  Let cursor changes to distract the user with.

**Comment by rsargent** [comment]
I have updated environmentaldata.org
to aeb9c5db3c91d38074ef179c2378551c403b14a0, from 7:35pm

**Comment by rsargent** [comment]
Confirming this is fixed, congrats tracking this down!  Confirmed on an Intel graphics Windows laptop that showed the bug earlier today.

**Comment by AnaHoffman** [comment]
Just double checked on my computer and it's working great and I'm ready to
roll!
Thanks for fixing this biggie!

Best,
Ana Hoffman
CREATE Lab
Email: ana@createlab.org
Cell: (304) 231-7547

**Comment by rsargent** [comment]
Split @pdille's comment about google maps markers into @46
